# Generated by Django 3.1 on 2020-08-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('size', models.IntegerField(choices=[
                 (0, 0), (1, 1), (2, 2), (3, 3), (4, 4),
                 (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('photo', models.ImageField(upload_to='shoes')),
            ],
        ),
    ]
